### PR TITLE
Lots of Fixes

### LINKED ISSUE #39: Consider 'npm ci'
https://github.com/Root16/bamboo/blob/1ee958eda68f17ac355b680518cf8f4a48ab794c/.github/workflows/build-test-extension.yaml#L13

### LINKED ISSUE #40: Extension failes When Workspace is Undefined

### LINKED ISSUE #41: Should Authenticate automatically on Startup
Otherwise, authentication is broken

### LINKED ISSUE #42: Tree view should have the file on disk set
SHould be:

```
> new_/web-resources/account.js
     /build/main.js
```

### LINKED ISSUE #43: README UPDATES
- dont include the publisher in example
- example of mappings needs to be switched (file on disk is on the left)
- 'bamboo.config.json'

### PR DESCRIPTION
**Pull request by johnyenter-briars**
Closes #43 
Closes #40 
Closes #39 
Closes #41 
Closes #42 

image

### CODE REVIEW

File: src/classes/treeview/WebResourcesProvider.ts [hunk 1]
```diff
@@ -15,18 +17,33 @@ export class WebResourcesProvider implements vscode.TreeDataProvider<WebResource
...
-                vscode.TreeItemCollapsibleState.Collapsed
-            ));
 
-            return Promise.resolve(mapped);
+            var mapped = Promise.all(webresources.map(async r => {
+                var webResource = new WebResource(r.name, r.id, true,
+                    vscode.TreeItemCollapsibleState.Collapsed
+                );
+
+                var pathInPAWithoutPublisher = r.name.split("_")[1];
```
Comment (plohm12) [inline src/classes/treeview/WebResourcesProvider.ts:36]: Maybe revise this to something like x.substring(x.indexOf("\_")) in case a web resource has other underscores in it's path, like new_/form_scripts/main_account.js

**Comment by johnyenter-briars** [comment]
@plohm12 Should be ready for a re-review when you get the chance plz 🥺

**Review by plohm12 — APPROVED** [review]
